### ISSUE TITLE
Layout options freezes most functions

### ISSUE THREAD

**Issue by chrisfperes** [adminfaces/admin-starter-springboot#4]
When some of the options in lateral layout options menu are toggle, both lateral menus stop working, this only fixes when I clean the browser caches. I tested it on Chrome.

**Comment by rmpestano** [comment]
Yes, also ajax call are not triggered anymore, no javascript errors thou. 

I need to investigate further as it doesn't happen on other starters (tomcat/javaee/javaee-security).

Thanks for reporting.

**Comment by rmpestano** [comment]
Hi @chrisfperes, can you try the fix below?

https://github.com/adminfaces/admin-starter-springboot/commit/84f10c5f9fd01ced9e72a06b431f494df93737b7#diff-6937490b8ef42332c03bbfbc492073a8R60

**Comment by rmpestano** [comment]
Forget it, it only fixes the control sidebar opening issue but the ajax calls and left hamburger menu still not working.

**Comment by rmpestano** [comment]
Alright, now I think I got it working. Had to update OmniFaces (and weld) to v3.0, take a look at this branch: https://github.com/adminfaces/admin-starter-springboot/blob/omnifaces3/pom.xml and compare with your pom.xml to configure omnifaces 3.

If you want to test locally just clone omnifaces3 branch:

```
git clone -b omnifaces3 https://github.com/adminfaces/admin-starter-springboot
```

if you already have cloned the starter just do a `git checkout -f omnifaces3`

I hope it helps.

**Comment by chrisfperes** [comment]
It's working fine now, thanks for helping!

**Comment by persapiens** [comment]
hi @chrisfperes and @rmpestano 

Which application server do you use to run `omnifaces3` branch successfully? I tried with `java -jar target/admin-starter.war` but login failed.

I look forward your answer.

**Comment by rmpestano** [comment]
Hi @persapiens, I'm just using `mvn spring-boot:run` and it is just working.

If it still doesn't work for you, try attached zip:

[admin-starter-springboot-omni3.zip](https://github.com/adminfaces/admin-starter-springboot/files/2611467/admin-starter-springboot-omni3.zip)

**Comment by rmpestano** [comment]
From the logs it is using embedded tomcat:

```
2018-11-23 16:10:08.909  INFO 14789 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2018-11-23 16:10:08.935  INFO 14789 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-11-23 16:10:08.936  INFO 14789 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.34
```

**Comment by rmpestano** [comment]
Hi guys,

Thanks to @persapiens [PR](https://github.com/adminfaces/admin-template/pull/138) this issue is **almost** fixed.

We're still facing the very same issue when `a skin is changed` via the controlsidebar. 

As before it doesn't happen on omnifaces3 branch, JavaEE admin-starter or admin-starter-tomcat.

@persapiens, can you have a look? the skin changing was moved [to admin-base](https://github.com/adminfaces/admin-template/blob/master/src/main/resources/META-INF/resources/admin-base.xhtml#L189-L448), (for details see adminfaces/admin-template#140). 

PS: I'm watting to release vRC20 so this fix gets included.

**Comment by persapiens** [comment]
hi @rmpestano ,
`omnifaces3` branch is not perfect. It works ok with `skin change` but it skips login if you run it with `mvn spring-boot:run`. More, `omnifaces3` branch login does not work if you run it with `java -jar target/admin-starter.war`.

`master` branch breaks `skin change` indeed. I've played a bit with broken implementation
```xhtml
<p:commandLink id="btn-skin-purple" styleClass="skin-link clearfix #{skinMB.skin eq 'skin-purple' ? '':'full-opacity-hover'}"
  oncomplete="replaceSkinWith('skin-purple');updateSkinPurple()"
  process="@none" update="@none" global="false" partialSubmit="true">
  <div>
    <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-purple-active"></span>
    <span class="bg-purple" style="display:block; width: 80%; float: left; height: 7px;"></span>
  </div>
  <div>
    <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32"></span>
    <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span>
  </div>
</p:commandLink>
<p:remoteCommand name="updateSkinPurple" action="#{skinMB.changeSkin('skin-purple')}" process="@this" update="@none" global="false"/>
```
It is strange that if I remove `oncomplete="replaceSkinWith('skin-purple');updateSkinPurple()"`, controlsidebar breaks!

**Comment by rmpestano** [comment]
Hi @persapiens,

> ...It works ok with skin change but it skips login...

Yes, it is probably not recognizing AdminSession specialization on [LoginMB](https://github.com/adminfaces/admin-starter-springboot/blob/master/src/main/java/com/github/adminfaces/starter/infra/security/LogonMB.java#L34) because the AdminFilter is active but is considering user is always logged in which is the default behaviour. LoginMB is responsible for telling AdminFaces that user is not logged in.

> More, omnifaces3 branch login does not work if you run it with java -jar target/admin-starter.war.

For some reason when using java -jar SpringBoot uses omnifaces1 and that's probably why it's not working with java -jar:

```
2018-11-27 09:45:48.121  INFO 4148 --- [ost-startStop-1] o.omnifaces.VersionLoggerEventListener   : Using OmniFaces version 1.14.1

```

> It is strange that if I remove oncomplete="replaceSkinWith('skin-purple');updateSkinPurple()", controlsidebar breaks!
 
The controlsidebar is a bit complex component because it uses LocalStorage for persisting user preferences ([see here](https://github.com/adminfaces/admin-template/blob/df3ffd61cc0ba8919ed7de03ecdce78fd8ac2edf/src/main/resources/META-INF/resources/js/control-sidebar.js#L182), the ` get('layout.skin');` loads from browser storage - loadSkin is called on documentReady)  but at the same time AdminFaces binds the current skin in [skinMB](https://github.com/adminfaces/admin-template/blob/df3ffd61cc0ba8919ed7de03ecdce78fd8ac2edf/src/main/resources/META-INF/resources/admin-base.xhtml#L22) so we can [reset defaults](https://github.com/adminfaces/admin-template/blob/df3ffd61cc0ba8919ed7de03ecdce78fd8ac2edf/src/main/java/com/github/adminfaces/template/bean/LayoutMB.java#L65) by [loading skin from admin-config.properties](https://github.com/adminfaces/admin-template/blob/df3ffd61cc0ba8919ed7de03ecdce78fd8ac2edf/src/main/java/com/github/adminfaces/template/bean/SkinMB.java#L27).

**Comment by persapiens** [comment]
When I run `omnifaces` branch using `java -jar admin-starter.war`, I see OmniFaces 3.2
```
2018-11-27 15:50:17.566  INFO 21653 --- [ost-startStop-1] org.omnifaces.ApplicationInitializer     : Using OmniFaces version 3.2
```

**Comment by rmpestano** [comment]
> When I run omnifaces branch using java -jar admin-starter.war, I see OmniFaces 3.2

You're right, I was running against an old war file on target. Same thing for me here, the login is not working with java -jar on the other hand using mvn spring-boot:run the login page is skipped and looks like LoginMB is not being used on this case.

**Comment by rmpestano** [comment]
Guys, I think I got it working with OmniFaces1, can you try on the master branch of this repo?

**Comment by persapiens** [comment]
> Guys, I think I got it working with OmniFaces1, can you try on the master branch of this repo?

It works. Great work.

**Comment by rmpestano** [comment]
RC20 was released, I'll close the issue. Thank you very much guys for your help here!
